### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mooreds** [macdonst/AppPreferences#2]
Hi,

I forked your AppPreferences PhoneGap plugin to make it work with plugman.  I was wondering if you would give this code an explicit license (was thinking Apache 2.0: http://www.apache.org/licenses/LICENSE-2.0 because that is what cordova is licensed under).

Thanks.

**Comment by mooreds** [comment]
Whoops, I missed the MIT license at the bottom of the readme.  My bad.

**Comment by macdonst** [comment]
If you end up getting it to work with plug man submit a pul request.i was
going to start on plug manning all my plugins post PhoneGap day in July.

Simon

On Wednesday, July 3, 2013, mooreds wrote:

> Whoops, I missed the MIT license at the bottom of the readme. My bad.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/macdonst/AppPreferences/issues/2#issuecomment-20455746
> .

## 

Simon Mac Donald
http://hi.im/simonmacdonald
